Cldp 11 reset password
Dystraite/dystraite_front pull request #13
Opened 2021-02-17 13:22 UTC by matteolecuit

Add reset password procedure

![image](https://user-images.githubusercontent.com/23716847/108210218-8c852300-712b-11eb-88d6-6ff803f4026c.png)
![image](https://user-images.githubusercontent.com/23716847/108210256-960e8b00-712b-11eb-828f-ef56e268ec34.png)

2021-02-18 17:25 UTC, PaulLereverend commented
Dans le mail qui m'a été envoyé le lien était http://localhost:4200/reset-password/96394c2f-6427-49ca-86f6-cfae368f6c2d
or la route /reset-password n'existe pas, côté front c'est /change-password
En mettant la bonne route, tout fonctionne bien.

2021-02-18 17:27 UTC, PaulLereverend commented
![image](https://user-images.githubusercontent.com/10038398/108396160-d5fe6c80-7216-11eb-83b2-b61ebad31ff2.png)
Petit problème de CSS également, espacer les inputs améliorerais la lisibilité.

2021-02-18 17:45 UTC, PaulLereverend commented
Le titre du mail `Password reset code` est en anglais, est-ce qu'il serait pas mieux de le mettre en français ? Et également de le mettre dans la conf ?

2021-02-18 17:46 UTC, PaulLereverend requested changes
voir commentaires

2021-02-18 18:02 UTC, matteolecuit commented
> Le titre du mail `Password reset code` est en anglais, est-ce qu'il serait pas mieux de le mettre en français ? Et également de le mettre dans la conf ?

Ok, à changer sur le back

2021-02-18 18:03 UTC, matteolecuit commented
> Le titre du mail `Password reset code` est en anglais, est-ce qu'il serait pas mieux de le mettre en français ? Et également de le mettre dans la conf ?

En effet, je change ça

2021-02-20 15:40 UTC, matteolecuit commented
> Dans le mail qui m'a été envoyé le lien était http://localhost:4200/reset-password/96394c2f-6427-49ca-86f6-cfae368f6c2d
> or la route /reset-password n'existe pas, côté front c'est /change-password
> En mettant la bonne route, tout fonctionne bien.

J'ai changé ça mercredi déjà (sur la branche dev)

2021-02-20 15:57 UTC, matteolecuit commented
J'ai mis à jour le CSS, et les changements pour le back son push sur develop

2021-02-21 08:35 UTC, merged